namespace Marketify.CatalogImport;

public static class RichHouseCatalogManifest
{
    private static readonly DateTimeOffset SummerOfferStart = new(2026, 7, 20, 0, 0, 0, TimeSpan.FromHours(2));
    private static readonly DateTimeOffset SummerOfferEnd = new(2026, 8, 31, 23, 59, 59, TimeSpan.FromHours(2));

    public static IReadOnlyList<RichHouseCategorySeedDefinition> Categories { get; } =
    [
        new(
            "Suits",
            "suits",
            "Tailored suits and refined formal sets curated for modern menswear dressing.",
            10,
            "Men's Suits | Rich House",
            "Premium men's suits curated by Rich House, from double-breasted tailoring to versatile formal sets."),
        new(
            "Wedding Suits",
            "wedding-suits",
            "Statement tuxedos and occasionwear built for weddings, engagements, and black-tie evenings.",
            20,
            "Wedding Suits | Rich House",
            "Discover Rich House wedding suits and tuxedos for formal celebrations and elevated evening wear."),
        new(
            "T-Shirts",
            "t-shirts",
            "Casual cotton staples for off-duty looks and relaxed weekend styling.",
            30,
            "Men's T-Shirts | Rich House",
            "Premium casual T-shirts from Rich House, styled for modern everyday wear."),
        new(
            "Shoes",
            "shoes",
            "Formal footwear selected to finish tailored looks with a polished profile.",
            40,
            "Men's Shoes | Rich House",
            "Formal men's shoes from Rich House designed to complement suits and occasionwear.")
    ];

    public static IReadOnlyList<RichHouseProductSeedDefinition> Products { get; } =
    [
        BuildSuit(
            importKey: "rich-house-forest-pinstripe-double-breasted-suit",
            name: "Forest Pinstripe Double-Breasted Suit",
            slug: "forest-pinstripe-double-breasted-suit",
            sku: "RH-SUIT-001",
            shortDescription: "A structured forest-green pinstripe suit with a sharp double-breasted front.",
            description: "Provisional catalog entry inferred from the supplied photography. This tailored suit pairs a forest-green base with a refined pinstripe finish and a dressier double-breasted silhouette suited to formal appointments and elevated evening styling.",
            price: 8490m,
            compareAtPrice: 9490m,
            offerPrice: 7990m,
            offerStart: SummerOfferStart,
            offerEnd: SummerOfferEnd,
            isFeatured: true,
            isBestSeller: true,
            isNewArrival: false,
            colorName: "Forest Green",
            colorSlug: "forest-green",
            sourceFiles: ["DSC_1226.jpg", "DSC_1227.jpg", "DSC_1230.jpg", "DSC_1231.jpg", "DSC_1237.jpg"]),
        BuildSuit(
            importKey: "rich-house-light-grey-three-piece-suit",
            name: "Light Grey Three-Piece Suit",
            slug: "light-grey-three-piece-suit",
            sku: "RH-SUIT-002",
            shortDescription: "A light-grey formal suit styled with a waistcoat for all-day occasion wear.",
            description: "Provisional catalog entry inferred from the supplied photography. This light-grey suit is positioned as a clean, versatile formal option with a classic three-piece presentation and a polished silhouette.",
            price: 6790m,
            compareAtPrice: 7590m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: false,
            isBestSeller: false,
            isNewArrival: true,
            colorName: "Light Grey",
            colorSlug: "light-grey",
            sourceFiles: ["DSC_1243.jpg"]),
        BuildSuit(
            importKey: "rich-house-sand-beige-three-piece-suit",
            name: "Sand Beige Three-Piece Suit",
            slug: "sand-beige-three-piece-suit",
            sku: "RH-SUIT-003",
            shortDescription: "A warm sand-beige suit with a soft formal finish and matching waistcoat.",
            description: "Provisional catalog entry inferred from the supplied photography. This three-piece look leans into a softer beige palette that works well for daytime celebrations, summer tailoring, and polished smart-formal dressing.",
            price: 6990m,
            compareAtPrice: 7790m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: true,
            isBestSeller: false,
            isNewArrival: true,
            colorName: "Sand Beige",
            colorSlug: "sand-beige",
            sourceFiles: ["DSC_1255.jpg", "DSC_1260.jpg", "DSC_1263.jpg"]),
        BuildSuit(
            importKey: "rich-house-navy-pinstripe-double-breasted-suit",
            name: "Navy Pinstripe Double-Breasted Suit",
            slug: "navy-pinstripe-double-breasted-suit",
            sku: "RH-SUIT-004",
            shortDescription: "A navy pinstripe suit finished with a strong double-breasted profile.",
            description: "Provisional catalog entry inferred from the supplied photography. This navy pinstripe suit is positioned as a confident formal staple with a sharper double-breasted line and timeless boardroom-to-event appeal.",
            price: 8990m,
            compareAtPrice: 9990m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: true,
            isBestSeller: true,
            isNewArrival: false,
            colorName: "Navy",
            colorSlug: "navy",
            sourceFiles: ["DSC_1269.jpg", "DSC_1272.jpg"]),
        BuildSuit(
            importKey: "rich-house-black-suit-grey-waistcoat",
            name: "Black Suit with Grey Waistcoat",
            slug: "black-suit-grey-waistcoat",
            sku: "RH-SUIT-005",
            shortDescription: "A black tailored suit layered over a contrast grey waistcoat for formal depth.",
            description: "Provisional catalog entry inferred from the supplied photography. This outfit mixes a classic black suit with a contrast grey waistcoat, making it a strong option for eveningwear and dressed-up formal occasions.",
            price: 7890m,
            compareAtPrice: 8690m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: false,
            isBestSeller: true,
            isNewArrival: false,
            colorName: "Black",
            colorSlug: "black",
            sourceFiles: ["DSC_1279.jpg", "DSC_1281.jpg"]),
        BuildSuit(
            importKey: "rich-house-textured-cobalt-blue-suit",
            name: "Textured Cobalt Blue Suit",
            slug: "textured-cobalt-blue-suit",
            sku: "RH-SUIT-006",
            shortDescription: "A saturated blue suit with a textured finish for statement formal dressing.",
            description: "Provisional catalog entry inferred from the supplied photography. This textured cobalt-blue suit adds bold color to the lineup while keeping the overall cut firmly in the tailored formal space.",
            price: 7290m,
            compareAtPrice: 7990m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: true,
            isBestSeller: false,
            isNewArrival: true,
            colorName: "Cobalt Blue",
            colorSlug: "cobalt-blue",
            sourceFiles: ["DSC_1287.jpg", "DSC_1288.jpg"]),
        BuildSuit(
            importKey: "rich-house-black-paisley-three-piece-suit",
            name: "Black Three-Piece Suit",
            slug: "black-three-piece-suit",
            sku: "RH-SUIT-007",
            shortDescription: "A black three-piece formal suit styled for dress occasions and evening events.",
            description: "Provisional catalog entry inferred from the supplied photography. This black three-piece suit anchors the core formal range with a clean dark palette and versatile special-occasion presentation.",
            price: 7590m,
            compareAtPrice: 8390m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: false,
            isBestSeller: true,
            isNewArrival: false,
            colorName: "Black",
            colorSlug: "black",
            sourceFiles: ["DSC_1292.jpg"]),
        BuildWeddingSuit(
            importKey: "rich-house-ivory-dinner-jacket-tuxedo",
            name: "Ivory Dinner Jacket Tuxedo",
            slug: "ivory-dinner-jacket-tuxedo",
            sku: "RH-TUX-001",
            shortDescription: "An ivory dinner jacket tuxedo styled for weddings and black-tie celebrations.",
            description: "Provisional catalog entry inferred from the supplied photography. This tuxedo pairs an ivory dinner jacket with strong black detailing to create a high-contrast wedding and eveningwear option.",
            price: 9290m,
            compareAtPrice: 10290m,
            offerPrice: 8790m,
            offerStart: SummerOfferStart,
            offerEnd: SummerOfferEnd,
            isFeatured: true,
            isBestSeller: true,
            isNewArrival: false,
            colorName: "Ivory",
            colorSlug: "ivory",
            sourceFiles: ["DSC_1299.jpg", "DSC_1303.jpg"]),
        BuildSuit(
            importKey: "rich-house-light-grey-contrast-waistcoat-suit",
            name: "Light Grey Contrast Waistcoat Suit",
            slug: "light-grey-contrast-waistcoat-suit",
            sku: "RH-SUIT-008",
            shortDescription: "A light-grey suit styled with a darker contrast waistcoat for elevated tailoring.",
            description: "Provisional catalog entry inferred from the supplied photography. This look keeps the light-grey suit base but introduces a darker waistcoat treatment, giving it a sharper occasionwear feel than the softer daytime set.",
            price: 7390m,
            compareAtPrice: 8190m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: false,
            isBestSeller: false,
            isNewArrival: true,
            colorName: "Light Grey",
            colorSlug: "light-grey",
            sourceFiles: ["DSC_1307.jpg"]),
        BuildSuit(
            importKey: "rich-house-camel-double-breasted-suit",
            name: "Camel Double-Breasted Suit",
            slug: "camel-double-breasted-suit",
            sku: "RH-SUIT-009",
            shortDescription: "A camel-toned double-breasted suit with a dressier statement silhouette.",
            description: "Provisional catalog entry inferred from the supplied photography. This camel suit leans warmer and more expressive, giving the catalog a polished earth-tone option for special occasions and standout tailoring.",
            price: 7190m,
            compareAtPrice: 7890m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: false,
            isBestSeller: false,
            isNewArrival: true,
            colorName: "Camel",
            colorSlug: "camel",
            sourceFiles: ["DSC_1314.jpg", "DSC_1316.jpg"]),
        BuildSuit(
            importKey: "rich-house-tobacco-three-piece-suit",
            name: "Tobacco Three-Piece Suit",
            slug: "tobacco-three-piece-suit",
            sku: "RH-SUIT-010",
            shortDescription: "A tobacco-brown three-piece suit that adds depth to the tailored lineup.",
            description: "Provisional catalog entry inferred from the supplied photography. This tobacco-brown suit is positioned as a richer formal option that sits between classic neutrals and more expressive seasonal tailoring.",
            price: 6890m,
            compareAtPrice: 7590m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: false,
            isBestSeller: false,
            isNewArrival: true,
            colorName: "Tobacco Brown",
            colorSlug: "tobacco-brown",
            sourceFiles: ["DSC_1362.jpg", "DSC_1365.jpg"]),
        BuildWeddingSuit(
            importKey: "rich-house-black-velvet-trim-tuxedo",
            name: "Black Velvet-Trim Tuxedo",
            slug: "black-velvet-trim-tuxedo",
            sku: "RH-TUX-002",
            shortDescription: "A formal black tuxedo with velvet-trim styling and a clean bow-tie finish.",
            description: "Provisional catalog entry inferred from the supplied photography. This black tuxedo is aimed at black-tie dressing with contrast trim, a bow tie presentation, and a sharper eveningwear silhouette.",
            price: 9790m,
            compareAtPrice: 10890m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: true,
            isBestSeller: true,
            isNewArrival: false,
            colorName: "Black",
            colorSlug: "black",
            sourceFiles: ["DSC_1418.jpg", "DSC_1423.jpg"]),
        BuildTShirt(
            importKey: "rich-house-purple-graphic-cotton-t-shirt",
            name: "Purple Graphic Cotton T-Shirt",
            slug: "purple-graphic-cotton-t-shirt",
            sku: "RH-TEE-001",
            shortDescription: "A casual purple graphic tee added as a softer off-duty counterpoint to the tailoring.",
            description: "Provisional catalog entry inferred from the supplied photography. This relaxed T-shirt brings a casual cotton option into the catalog and is best treated as an editable placeholder pending final merchandising review.",
            price: 790m,
            compareAtPrice: 950m,
            offerPrice: null,
            offerStart: null,
            offerEnd: null,
            isFeatured: false,
            isBestSeller: false,
            isNewArrival: true,
            colorName: "Purple",
            colorSlug: "purple",
            sourceFiles: ["DSC_1470.jpg", "DSC_1471.jpg", "DSC_1473.jpg", "DSC_1476.jpg", "DSC_1477.jpg"]),
        BuildShoes(
            importKey: "rich-house-black-patent-derby-shoes",
            name: "Black Patent Derby Shoes",
            slug: "black-patent-derby-shoes",
            sku: "RH-SHOE-001",
            shortDescription: "A glossy black derby pair designed to finish formal looks cleanly.",
            description: "Provisional catalog entry inferred from the supplied photography. This footwear entry represents the polished black derby pair shown in the supplied detail photography and rounds out the formal outfit offering.",
            price: 2890m,
            compareAtPrice: 3290m,
            offerPrice: 2490m,
            offerStart: SummerOfferStart,
            offerEnd: SummerOfferEnd,
            isFeatured: true,
            isBestSeller: false,
            isNewArrival: true,
            colorName: "Black",
            colorSlug: "black",
            sourceFiles: ["photo_2026-07-24_16-36-25.jpg", "photo_2026-07-24_16-36-29.jpg", "photo_2026-07-24_16-36-32.jpg"])
    ];

    public static IReadOnlyDictionary<string, string> CategoryCoverProductKeys { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["suits"] = "rich-house-forest-pinstripe-double-breasted-suit",
        ["wedding-suits"] = "rich-house-ivory-dinner-jacket-tuxedo",
        ["t-shirts"] = "rich-house-purple-graphic-cotton-t-shirt",
        ["shoes"] = "rich-house-black-patent-derby-shoes"
    };

    private static RichHouseProductSeedDefinition BuildSuit(
        string importKey,
        string name,
        string slug,
        string sku,
        string shortDescription,
        string description,
        decimal price,
        decimal? compareAtPrice,
        decimal? offerPrice,
        DateTimeOffset? offerStart,
        DateTimeOffset? offerEnd,
        bool isFeatured,
        bool isBestSeller,
        bool isNewArrival,
        string colorName,
        string colorSlug,
        IReadOnlyList<string> sourceFiles)
    {
        return new RichHouseProductSeedDefinition(
            importKey,
            name,
            slug,
            sku,
            "suits",
            shortDescription,
            description,
            price,
            compareAtPrice,
            offerPrice,
            offerStart,
            offerEnd,
            isFeatured,
            isBestSeller,
            isNewArrival,
            colorName,
            colorSlug,
            BuildVariants(("46", 2), ("48", 3), ("50", 4), ("52", 4), ("54", 3), ("56", 2), ("58", 1), ("60", 1)),
            sourceFiles);
    }

    private static RichHouseProductSeedDefinition BuildWeddingSuit(
        string importKey,
        string name,
        string slug,
        string sku,
        string shortDescription,
        string description,
        decimal price,
        decimal? compareAtPrice,
        decimal? offerPrice,
        DateTimeOffset? offerStart,
        DateTimeOffset? offerEnd,
        bool isFeatured,
        bool isBestSeller,
        bool isNewArrival,
        string colorName,
        string colorSlug,
        IReadOnlyList<string> sourceFiles)
    {
        return new RichHouseProductSeedDefinition(
            importKey,
            name,
            slug,
            sku,
            "wedding-suits",
            shortDescription,
            description,
            price,
            compareAtPrice,
            offerPrice,
            offerStart,
            offerEnd,
            isFeatured,
            isBestSeller,
            isNewArrival,
            colorName,
            colorSlug,
            BuildVariants(("46", 1), ("48", 2), ("50", 3), ("52", 3), ("54", 2), ("56", 2), ("58", 1)),
            sourceFiles);
    }

    private static RichHouseProductSeedDefinition BuildTShirt(
        string importKey,
        string name,
        string slug,
        string sku,
        string shortDescription,
        string description,
        decimal price,
        decimal? compareAtPrice,
        decimal? offerPrice,
        DateTimeOffset? offerStart,
        DateTimeOffset? offerEnd,
        bool isFeatured,
        bool isBestSeller,
        bool isNewArrival,
        string colorName,
        string colorSlug,
        IReadOnlyList<string> sourceFiles)
    {
        return new RichHouseProductSeedDefinition(
            importKey,
            name,
            slug,
            sku,
            "t-shirts",
            shortDescription,
            description,
            price,
            compareAtPrice,
            offerPrice,
            offerStart,
            offerEnd,
            isFeatured,
            isBestSeller,
            isNewArrival,
            colorName,
            colorSlug,
            BuildVariants(("S", 2), ("M", 3), ("L", 4), ("XL", 3), ("XXL", 2)),
            sourceFiles);
    }

    private static RichHouseProductSeedDefinition BuildShoes(
        string importKey,
        string name,
        string slug,
        string sku,
        string shortDescription,
        string description,
        decimal price,
        decimal? compareAtPrice,
        decimal? offerPrice,
        DateTimeOffset? offerStart,
        DateTimeOffset? offerEnd,
        bool isFeatured,
        bool isBestSeller,
        bool isNewArrival,
        string colorName,
        string colorSlug,
        IReadOnlyList<string> sourceFiles)
    {
        return new RichHouseProductSeedDefinition(
            importKey,
            name,
            slug,
            sku,
            "shoes",
            shortDescription,
            description,
            price,
            compareAtPrice,
            offerPrice,
            offerStart,
            offerEnd,
            isFeatured,
            isBestSeller,
            isNewArrival,
            colorName,
            colorSlug,
            BuildVariants(("40", 1), ("41", 2), ("42", 3), ("43", 3), ("44", 2), ("45", 1)),
            sourceFiles);
    }

    private static IReadOnlyList<RichHouseVariantSeedDefinition> BuildVariants(params (string SizeName, int StockQuantity)[] definitions)
    {
        return definitions
            .Select(definition => new RichHouseVariantSeedDefinition(definition.SizeName, definition.StockQuantity))
            .ToList();
    }
}
